import { Box, VStack } from "@chakra-ui/react";
import Head from "next/head";
import { Header, Footer } from "..";

const Layout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Blog | Robert A. Wilson</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <VStack width="100vw" height="100vh" spacing={0} align="stretch">
        <Header />

        <Box as="main" width="full" height="full">
          {children}
        </Box>

        <Footer />
      </VStack>
    </>
  );
};

export default Layout;
