import React from "react";
import Head from "next/head";
import { Flex, Spacer, VStack } from "@chakra-ui/react";
import { Header, Footer } from "..";

const Layout: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <>
    <Head>
      <title>Blog | Robert A. Wilson</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <VStack width="100vw" height="100vh" spacing={0} align="stretch">
      <Header />

      <Flex as="main" width="full" height="full" flexDirection="column">
        {children}
        <Spacer />
      </Flex>

      <Footer />
    </VStack>
  </>
);

export default Layout;
