import { Box, Heading, Link, Stack, Text } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box as="main">
        <Heading as="h1">
          Welcome to{" "}
          <Link href="https://nextjs.org" isExternal>
            Next.js!
          </Link>
        </Heading>

        <Text>
          Get started by editing <code>pages/index.tsx</code>
        </Text>

        <Stack spacing={8}>
          <Link href="https://nextjs.org/docs" isExternal>
            <Heading as="h2">Documentation &rarr;</Heading>
            <Text>
              Find in-depth information about Next.js features and API.
            </Text>
          </Link>

          <Link href="https://nextjs.org/learn">
            <Heading as="h2">Learn &rarr;</Heading>
            <Text>
              Learn about Next.js in an interactive course with quizzes!
            </Text>
          </Link>

          <Link href="https://github.com/vercel/next.js/tree/canary/examples">
            <Heading as="h2">Examples &rarr;</Heading>
            <Text>
              Discover and deploy boilerplate example Next.js projects.
            </Text>
          </Link>

          <Link href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app">
            <Heading as="h2">Deploy &rarr;</Heading>
            <Text>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </Text>
          </Link>
        </Stack>
      </Box>

      <Box as="footer">
        <Link
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <Box as="span">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </Box>
        </Link>
      </Box>
    </Box>
  );
};

export default Home;
